### ISSUE TITLE
请求代码

### ISSUE THREAD

**Issue by adsadaasd** [yeshenpy/RACE#2]
你好，我是安徽大学的研究生，我想问您要一下RACE的majoco代码，想要学习一下

**Comment by yeshenpy** [comment]
好的，等我整理一下发给你。

**Comment by yeshenpy** [comment]
能否发一下你的邮箱给我，或者通过知乎等其他途径发给我也可以，代码还稍微有点乱，这几天忙完手头的事情，我发给你一个之前的版本。

**Comment by adsadaasd** [comment]
***@***.***，&nbsp;qq是1572057710，能加我一下吗，有的代码问题我想请教您一下，不会耽误您太长时间




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshenpy/RACE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月28日(星期四) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeshenpy/RACE] 请求代码 (Issue #2)





 
能否发一下你的邮箱给我，或者通过知乎等其他途径发给我也可以，代码还稍微有点乱，这几天忙完手头的事情，我发给你一个之前的版本。

**Comment by adsadaasd** [comment]
您好，我在上面打出邮箱他显示不出来，可以加一下qq或者微信吗，qq是1572057710，微信是19855143270，我的邮箱就是qq号加个后缀就行，没别的意思，就想请教您一下，我这方面不是特别懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshenpy/RACE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月28日(星期四) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeshenpy/RACE] 请求代码 (Issue #2)





 
能否发一下你的邮箱给我，或者通过知乎等其他途径发给我也可以，代码还稍微有点乱，这几天忙完手头的事情，我发给你一个之前的版本。
