### ISSUE TITLE
Mujoco repo is inaccessible

### ISSUE THREAD

**Issue by Sun-Licheng** [yeshenpy/RACE#4]
Hi
The Mujoco repo is inaccessible. Can you please share the ma-mujoco code for RACE?
You can send me the working code with instructions to run on my email: licheng_sun@126.com

Thanks.

**Comment by yeshenpy** [comment]
The code has been sent over. If you find it useful, please cite our work. Thank you very much.

**Comment by Sun-Licheng** [comment]
Has it been sent to this email address：[licheng_sun@126.com](mailto:licheng_sun@126.com)？

**Comment by yeshenpy** [comment]
Yes.

**Comment by Sun-Licheng** [comment]
I found that I wrote the wrong email address, I am very sorry, dear author, could you please resend it 0.0 ? Thank you very much. this email address：[leecheng_sun@126.com](mailto:leecheng_sun@126.com)

**Comment by yeshenpy** [comment]
pls check it :）

**Comment by Sun-Licheng** [comment]
> pls check it :）

谢谢亲爱的作者，祝作者论文发到手软
